### PR TITLE
Add ExclusiveRewardFactory

### PR DESCRIPTION
**Pull request by ScreamingHawk**
Note: Inheritance requires changing the func visibility and adding virtual to `RewardFactory`'s `batchMint`. This change doesn't include updates to the gen and artifacts for `RewardFactory`. This ensures consistent deployment addresses for downstream libraries that depend on the current bytecode for `RewardFactory` (Skyweaver). 

I assume this is fine as Conquest and other bytecodes also appear outdated.

### CODE REVIEW

**Comment by Agusx1211** [comment]
> This change doesn't include updates to the gen and artifacts for RewardFactory. This ensures consistent deployment addresses for downstream libraries that depend on the current bytecode for RewardFactory (Skyweaver).

I think we shouldn't try to maintain a fixed bytecode directly commited into the repo, ideally once something goes to production, we add it to our contract deploy scripts.

```sol
mapping(uint256 => bool) public isMinted;
```

Can we use shifted values to store this? one storage slot can save 256 `isMinted`. It seems like a low hanging fruit optimization.

**Comment by PhABC** [comment]
Bit shit is not a bad idea, but not sure we have time for added complexity considering this is due for early Feb. Can it be done very simply in a way that is safe?

**Comment by Agusx1211** [comment]
@PhABC Uniswap has a very simple tried and tested implementation:

https://github.com/Uniswap/merkle-distributor/blob/master/contracts/MerkleDistributor.sol

**Comment by ScreamingHawk** [comment]
Merging and creating a ticket to fix bytecode inconsistencies

**Comment by Agusx1211** [comment]
LGTM

**Pull request merged**
